-- MySQL Script generated by MySQL Workbench
-- Wed Nov 30 21:38:31 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema vehicledealership
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema vehicledealership
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `vehicledealership` DEFAULT CHARACTER SET utf8 ;
USE `vehicledealership` ;

-- -----------------------------------------------------
-- Table `vehicledealership`.`Client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vehicledealership`.`Client` (
  `idclient` INT NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(20) NOT NULL,
  `lastName` VARCHAR(100) NOT NULL,
  `gender` VARCHAR(2) NOT NULL,
  `address` VARCHAR(200) NOT NULL,
  `phoneNumber` VARCHAR(20) NOT NULL,
  `email` VARCHAR(255) NULL,
  `dateOfBirth` DATE NOT NULL,
  `carsOwned` INT NULL DEFAULT 0,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  PRIMARY KEY (`idclient`));


-- -----------------------------------------------------
-- Table `vehicledealership`.`car`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vehicledealership`.`car` (
  `idcar` INT NOT NULL AUTO_INCREMENT,
  `manufacturer` VARCHAR(50) NOT NULL,
  `model` VARCHAR(100) NOT NULL,
  `color` VARCHAR(45) NOT NULL,
  `categorie` VARCHAR(45) NOT NULL,
  `nbDoors` INT NOT NULL,
  `price` FLOAT NOT NULL,
  `Discount` VARCHAR(4) NULL DEFAULT '0%',
  `sold` VARCHAR(10) NULL DEFAULT 'false',
  PRIMARY KEY (`idcar`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vehicledealership`.`CarsSold`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vehicledealership`.`CarsSold` (
  `idCarsSold` INT NOT NULL AUTO_INCREMENT,
  `dateOfSale` DATE NOT NULL,
  `Client_idclient` INT NOT NULL,
  `car_idcar` INT NOT NULL,
  PRIMARY KEY (`idCarsSold`),
  INDEX `fk_CarsSold_Client_idx` (`Client_idclient` ASC) VISIBLE,
  INDEX `fk_CarsSold_car1_idx` (`car_idcar` ASC) VISIBLE,
  CONSTRAINT `fk_CarsSold_Client`
    FOREIGN KEY (`Client_idclient`)
    REFERENCES `vehicledealership`.`Client` (`idclient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CarsSold_car1`
    FOREIGN KEY (`car_idcar`)
    REFERENCES `vehicledealership`.`car` (`idcar`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vehicledealership`.`Employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vehicledealership`.`Employee` (
  `idemployee` INT NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(20) NOT NULL,
  `lastName` VARCHAR(100) NOT NULL,
  `gender` VARCHAR(2) NOT NULL,
  `position` VARCHAR(80) NOT NULL,
  `salary` FLOAT NOT NULL,
  `address` VARCHAR(200) NOT NULL,
  `phoneNumber` VARCHAR(20) NOT NULL,
  `email` VARCHAR(255) NULL,
  `dateOfBirth` DATE NOT NULL,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  PRIMARY KEY (`idemployee`));


-- -----------------------------------------------------
-- Table `vehicledealership`.`dealership`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vehicledealership`.`dealership` (
  `iddealership` INT NOT NULL,
  `address` VARCHAR(200) NOT NULL,
  `openingHour` TIME NOT NULL,
  `closingHour` TIME NOT NULL,
  `license` VARCHAR(1000) NULL,
  `Employee_idemployee` INT NOT NULL,
  PRIMARY KEY (`iddealership`),
  UNIQUE INDEX `iddealership_UNIQUE` (`iddealership` ASC) VISIBLE,
  INDEX `fk_dealership_Employee1_idx` (`Employee_idemployee` ASC) VISIBLE,
  CONSTRAINT `fk_dealership_Employee1`
    FOREIGN KEY (`Employee_idemployee`)
    REFERENCES `vehicledealership`.`Employee` (`idemployee`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `vehicledealership`;

DELIMITER $$
USE `vehicledealership`$$
CREATE DEFINER = CURRENT_USER TRIGGER `vehicledealership`.`CarsSold_AFTER_INSERT` AFTER INSERT ON `CarsSold` FOR EACH ROW
BEGIN
Update Client
Set carsOwned = carsOwned + 1
Where idclient = Client_idclient;
END$$

USE `vehicledealership`$$
CREATE DEFINER = CURRENT_USER TRIGGER `vehicledealership`.`CarsSold_AFTER_INSERT_1` AFTER INSERT ON `CarsSold` FOR EACH ROW
BEGIN
update car
set sold = true
where idcar = car_idcar;
END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
